-- =============================================================================
-- Corridor migration inventory — Oxford crosswalk, school-district H3 xwalk,
-- and ANALYTICS.FACTS parents still referenced by corridor / H3 features.
--
-- Goal: move consumers off **ANALYTICS.FACTS** toward **TRANSFORM.DEV** +
-- **REFERENCE.GEOGRAPHY** + **SOURCE_PROD** contracts (see MIGRATION_LOG batch 032).
--
-- Run: snowsql -c pretium -f scripts/sql/migration/inventory_corridor_oxford_school_analytics_facts.sql
-- =============================================================================

-- ############################################################################
-- # OXFORD — landed crosswalk + dbt ref (semantic layer reads DEV only)
-- ############################################################################

USE DATABASE TRANSFORM;

SELECT 'TRANSFORM.DEV.OXFORD_CBSA_CROSSWALK' AS fqn, COUNT(*) AS row_count
FROM TRANSFORM.DEV.OXFORD_CBSA_CROSSWALK;

SELECT column_name, data_type
FROM INFORMATION_SCHEMA.COLUMNS
WHERE table_catalog = 'TRANSFORM' AND table_schema = 'DEV' AND UPPER(table_name) = 'OXFORD_CBSA_CROSSWALK'
ORDER BY ordinal_position;

SELECT 'TRANSFORM.DEV.REF_OXFORD_METRO_CBSA' AS fqn, COUNT(*) AS row_count
FROM TRANSFORM.DEV.REF_OXFORD_METRO_CBSA;

SELECT 'TRANSFORM_PROD.REF.OXFORD_CBSA_CROSSWALK' AS fqn, COUNT(*) AS row_count
FROM TRANSFORM_PROD.REF.OXFORD_CBSA_CROSSWALK;

-- ############################################################################
-- # SCHOOL DISTRICT ↔ H3 — SOURCE_PROD landing + REFERENCE mirror
-- # (pretium-ai-dbt **ANALYTICS.REF.SCHOOL_DISTRICT_H3_XWALK** may not exist or
-- #  may be unauthorized on some roles — prefer SOURCE_PROD + REFERENCE.)
-- ############################################################################

USE DATABASE SOURCE_PROD;

SELECT 'SOURCE_PROD.GEO.MAP_SCHOOLDISTRICT_H3' AS fqn, COUNT(*) AS row_count
FROM SOURCE_PROD.GEO.MAP_SCHOOLDISTRICT_H3;

USE DATABASE REFERENCE;

SELECT 'REFERENCE.GEOGRAPHY.REF_SCHOOL_DISTRICT_H3_XWALK' AS fqn, COUNT(*) AS row_count
FROM REFERENCE.GEOGRAPHY.REF_SCHOOL_DISTRICT_H3_XWALK;

SELECT column_name, data_type
FROM INFORMATION_SCHEMA.COLUMNS
WHERE table_catalog = 'REFERENCE' AND table_schema = 'GEOGRAPHY'
  AND UPPER(table_name) = 'REF_SCHOOL_DISTRICT_H3_XWALK'
ORDER BY ordinal_position;

-- Optional: pretium-ai-dbt ref build (schema **REF** under target database)
-- SELECT 'ANALYTICS.REF.SCHOOL_DISTRICT_H3_XWALK' AS fqn, COUNT(*) AS row_count
-- FROM ANALYTICS.REF.SCHOOL_DISTRICT_H3_XWALK;

-- ############################################################################
-- # ANALYTICS.FACTS — corridor **ref()** parents (pretium-ai-dbt `int_corridor_*`,
-- # `membership_corridor`, `ref_feature_corridor_*`). Replace with **TRANSFORM.DEV**
-- # (or vendor silver) equivalents as each model is ported.
-- #
-- # Suggested **TRANSFORM.DEV** / **REFERENCE** counterparts already populated
-- # (verify separately): **TRANSFORM.DEV.FACT_LODES_NEAREST_CENTER_H3_R8_ANNUAL**,
-- # **TRANSFORM.DEV.FACT_CENSUS_ACS5_H3_R8_SNAPSHOT**, **TRANSFORM.DEV.FACT_CHERRE_STOCK_H3_R8**,
-- # **TRANSFORM.DEV.FACT_STANFORD_SEDA_H3_R8_SNAPSHOT** — see
-- # `inventory_corridor_pipeline_critical.sql`.
-- ############################################################################

USE DATABASE ANALYTICS;

SELECT 'ANALYTICS.FACTS.FACT_CENSUS_ACS5_H3_R8_SNAPSHOT' AS fqn, COUNT(*) AS row_count FROM ANALYTICS.FACTS.FACT_CENSUS_ACS5_H3_R8_SNAPSHOT
UNION ALL SELECT 'ANALYTICS.FACTS.FACT_CHERRE_STOCK_H3_R8', COUNT(*) FROM ANALYTICS.FACTS.FACT_CHERRE_STOCK_H3_R8
UNION ALL SELECT 'ANALYTICS.FACTS.FACT_STANFORD_SEDA_H3_R8_SNAPSHOT', COUNT(*) FROM ANALYTICS.FACTS.FACT_STANFORD_SEDA_H3_R8_SNAPSHOT
UNION ALL SELECT 'ANALYTICS.FACTS.FACT_LODES_NEAREST_CENTER_H3_R8_ANNUAL', COUNT(*) FROM ANALYTICS.FACTS.FACT_LODES_NEAREST_CENTER_H3_R8_ANNUAL
UNION ALL SELECT 'ANALYTICS.FACTS.FACT_MARKERR_RENT_H3_R8_MONTHLY', COUNT(*) FROM ANALYTICS.FACTS.FACT_MARKERR_RENT_H3_R8_MONTHLY
UNION ALL SELECT 'ANALYTICS.FACTS.FACT_MARKERR_SFR_RENT_H3_R8_MONTHLY', COUNT(*) FROM ANALYTICS.FACTS.FACT_MARKERR_SFR_RENT_H3_R8_MONTHLY
UNION ALL SELECT 'ANALYTICS.FACTS.FACT_CHERRE_MF_H3_R8_SNAPSHOT', COUNT(*) FROM ANALYTICS.FACTS.FACT_CHERRE_MF_H3_R8_SNAPSHOT
UNION ALL SELECT 'ANALYTICS.FACTS.FACT_ZONDA_BTR_H3_R8_MONTHLY', COUNT(*) FROM ANALYTICS.FACTS.FACT_ZONDA_BTR_H3_R8_MONTHLY
UNION ALL SELECT 'ANALYTICS.FACTS.FACT_ZONDA_BTR_COUNTY_MONTHLY', COUNT(*) FROM ANALYTICS.FACTS.FACT_ZONDA_BTR_COUNTY_MONTHLY
UNION ALL SELECT 'ANALYTICS.FACTS.FACT_ZONDA_SFR_H3_R8_MONTHLY', COUNT(*) FROM ANALYTICS.FACTS.FACT_ZONDA_SFR_H3_R8_MONTHLY
UNION ALL SELECT 'ANALYTICS.FACTS.FACT_RCA_MF_TRANSACTIONS_COUNTY_MONTHLY', COUNT(*) FROM ANALYTICS.FACTS.FACT_RCA_MF_TRANSACTIONS_COUNTY_MONTHLY
UNION ALL SELECT 'ANALYTICS.FACTS.FACT_RCA_MF_TRANSACTIONS_H3_R8_MONTHLY', COUNT(*) FROM ANALYTICS.FACTS.FACT_RCA_MF_TRANSACTIONS_H3_R8_MONTHLY
UNION ALL SELECT 'ANALYTICS.FACTS.FACT_RCA_MF_CONSTRUCTION_COUNTY_MONTHLY', COUNT(*) FROM ANALYTICS.FACTS.FACT_RCA_MF_CONSTRUCTION_COUNTY_MONTHLY
UNION ALL SELECT 'ANALYTICS.FACTS.FACT_RCA_MF_CONSTRUCTION_H3_R8_MONTHLY', COUNT(*) FROM ANALYTICS.FACTS.FACT_RCA_MF_CONSTRUCTION_H3_R8_MONTHLY
UNION ALL SELECT 'ANALYTICS.FACTS.FACT_RCA_MF_DEBT_H3_R8_MONTHLY', COUNT(*) FROM ANALYTICS.FACTS.FACT_RCA_MF_DEBT_H3_R8_MONTHLY
UNION ALL SELECT 'ANALYTICS.FACTS.FACT_CHERRE_MLS_H3_R8_MONTHLY', COUNT(*) FROM ANALYTICS.FACTS.FACT_CHERRE_MLS_H3_R8_MONTHLY
UNION ALL SELECT 'ANALYTICS.FACTS.FACT_MARKERR_AMENITY_H3_R8_SNAPSHOT', COUNT(*) FROM ANALYTICS.FACTS.FACT_MARKERR_AMENITY_H3_R8_SNAPSHOT
UNION ALL SELECT 'ANALYTICS.FACTS.FACT_MARKERR_MF_PIPELINE_H3_R8_MONTHLY', COUNT(*) FROM ANALYTICS.FACTS.FACT_MARKERR_MF_PIPELINE_H3_R8_MONTHLY
UNION ALL SELECT 'ANALYTICS.FACTS.FACT_CHERRE_VACANT_H3_R8_SNAPSHOT', COUNT(*) FROM ANALYTICS.FACTS.FACT_CHERRE_VACANT_H3_R8_SNAPSHOT
ORDER BY 1;
