-- =============================================================================
-- Zillow — SOURCE_PROD.ZILLOW RAW_* row counts (batch inventory / §1.5)
--
-- Run from inner repo root:
--   snowsql -c pretium -f scripts/sql/migration/inventory_zillow_source_prod_raw.sql
--
-- Checklist: docs/migration/MIGRATION_TASKS_ZILLOW_TRANSFORM_DEV.md §1.5
-- =============================================================================

USE DATABASE SOURCE_PROD;
USE SCHEMA ZILLOW;

SELECT 'RAW_AFFORDABILITY' AS table_name, COUNT(*) AS row_count FROM RAW_AFFORDABILITY
UNION ALL SELECT 'RAW_DAYS_ON_MARKET_AND_PRICE_CUTS', COUNT(*) FROM RAW_DAYS_ON_MARKET_AND_PRICE_CUTS
UNION ALL SELECT 'RAW_FOR_SALE_LISTINGS', COUNT(*) FROM RAW_FOR_SALE_LISTINGS
UNION ALL SELECT 'RAW_HOME_VALUES', COUNT(*) FROM RAW_HOME_VALUES
UNION ALL SELECT 'RAW_HOME_VALUES_FORECASTS', COUNT(*) FROM RAW_HOME_VALUES_FORECASTS
UNION ALL SELECT 'RAW_MARKET_HEAT_INDEX', COUNT(*) FROM RAW_MARKET_HEAT_INDEX
UNION ALL SELECT 'RAW_NEW_CONSTRUCTION', COUNT(*) FROM RAW_NEW_CONSTRUCTION
UNION ALL SELECT 'RAW_RENTAL_FORECASTS', COUNT(*) FROM RAW_RENTAL_FORECASTS
UNION ALL SELECT 'RAW_RENTALS', COUNT(*) FROM RAW_RENTALS
UNION ALL SELECT 'RAW_SALES', COUNT(*) FROM RAW_SALES
ORDER BY table_name;
