-- =============================================================================
-- Quick Snowflake checks for semantic-layer concept models (run: snowsql -c pretium -f …)
-- =============================================================================

SELECT 'TRANSFORM.COSTAR.SCENARIOS' AS o, COUNT(*) AS n FROM TRANSFORM.COSTAR.SCENARIOS WHERE CBSA_CODE IS NOT NULL;
SELECT 'TRANSFORM.MARKERR.RENT_PROPERTY_CBSA_MONTHLY' AS o, COUNT(*) AS n FROM TRANSFORM.MARKERR.RENT_PROPERTY_CBSA_MONTHLY;
SELECT 'TRANSFORM.MARKERR.MARKERR_RENT_SFR zip' AS o, COUNT(*) AS n
FROM TRANSFORM.MARKERR.MARKERR_RENT_SFR WHERE UPPER(TRIM(GEOGRAPHY_TYPE)) = 'ZIPCODE';
SELECT 'HUD FACT_CBSA rows' AS o, COUNT(*) AS n
FROM TRANSFORM.DEV.FACT_HUD_HOUSING_SERIES WHERE GEO_LEVEL_CODE = 'cbsa';
SELECT 'CHERRE USA_AVM_GEO_STATS MA' AS o, COUNT(*) AS n
FROM TRANSFORM.CHERRE.USA_AVM_GEO_STATS WHERE GEOGRAPHY_TYPE = 'MA';
