-- TRANSFORM.DEV.FACT_MARKERR_RENT_SFR — **TRANSFORM.MARKERR.MARKERR_RENT_SFR** (explicit projection + casts; matches ``DESC TABLE`` contract 2026-04).
-- Grain: ``GEOGRAPHY_TYPE`` × ``GEO_ID`` × ``DATE`` × ``BATHROOM_COUNT``. Feeds ``concept_rent_market_monthly`` on ``ZIPCODE`` / ``RENT_ASKING_MEAN`` / ``GEOGRAPHY_TYPE``.
{{ config(
    alias='fact_markerr_rent_sfr',
    materialized='view',
    tags=['transform', 'transform_dev', 'markerr', 'fact_markerr'],
) }}

SELECT
    s."DATE"::DATE AS "DATE",
    TRIM(TO_VARCHAR(s.PROPERTY_TYPE)) AS PROPERTY_TYPE,
    UPPER(TRIM(TO_VARCHAR(s.GEOGRAPHY_TYPE))) AS GEOGRAPHY_TYPE,
    NULLIF(TRIM(TO_VARCHAR(s.GEO_ID)), '') AS GEO_ID,
    LPAD(TRIM(TO_VARCHAR(s.ZIPCODE)), 5, '0') AS ZIPCODE,
    TRIM(TO_VARCHAR(s.COUNTY)) AS COUNTY,
    TRIM(TO_VARCHAR(s.COUNTY_ID)) AS COUNTY_ID,
    TRY_TO_NUMBER(s.MSA_ID) AS MSA_ID,
    TRIM(TO_VARCHAR(s.MSA)) AS MSA,
    TRIM(TO_VARCHAR(s.MSA_NAME)) AS MSA_NAME,
    TRIM(TO_VARCHAR(s.BATHROOM_COUNT)) AS BATHROOM_COUNT,

    (s.TOTAL_UNITS + 0e0)::DOUBLE AS TOTAL_UNITS,
    (s.RENTER_OCCUPIED_UNITS + 0e0)::DOUBLE AS RENTER_OCCUPIED_UNITS,
    (s.SINGLE_FAMILY_UNITS + 0e0)::DOUBLE AS SINGLE_FAMILY_UNITS,

    (s.RENT_ASKING_MEAN + 0e0)::DOUBLE AS RENT_ASKING_MEAN,
    (s.RENT_ASKING_MEAN_MONTHLY_CHANGE + 0e0)::DOUBLE AS RENT_ASKING_MEAN_MONTHLY_CHANGE,
    (s.RENT_ASKING_MEAN_QUARTERLY_CHANGE + 0e0)::DOUBLE AS RENT_ASKING_MEAN_QUARTERLY_CHANGE,
    (s.RENT_ASKING_MEAN_1_YEAR_CHANGE + 0e0)::DOUBLE AS RENT_ASKING_MEAN_1_YEAR_CHANGE,
    (s.RENT_ASKING_MEAN_3_YEAR_CHANGE + 0e0)::DOUBLE AS RENT_ASKING_MEAN_3_YEAR_CHANGE,

    (s.RENT_ASKING_2_OR_LESS_BED_MEAN + 0e0)::DOUBLE AS RENT_ASKING_2_OR_LESS_BED_MEAN,
    (s.RENT_ASKING_2_OR_LESS_BED_MEAN_MONTHLY_CHANGE + 0e0)::DOUBLE AS RENT_ASKING_2_OR_LESS_BED_MEAN_MONTHLY_CHANGE,
    (s.RENT_ASKING_2_OR_LESS_BED_MEAN_QUARTERLY_CHANGE + 0e0)::DOUBLE AS RENT_ASKING_2_OR_LESS_BED_MEAN_QUARTERLY_CHANGE,
    (s.RENT_ASKING_2_OR_LESS_BED_MEAN_1_YEAR_CHANGE + 0e0)::DOUBLE AS RENT_ASKING_2_OR_LESS_BED_MEAN_1_YEAR_CHANGE,
    (s.RENT_ASKING_2_OR_LESS_BED_MEAN_3_YEAR_CHANGE + 0e0)::DOUBLE AS RENT_ASKING_2_OR_LESS_BED_MEAN_3_YEAR_CHANGE,

    (s.RENT_ASKING_3_BED_MEAN + 0e0)::DOUBLE AS RENT_ASKING_3_BED_MEAN,
    (s.RENT_ASKING_3_BED_MEAN_MONTHLY_CHANGE + 0e0)::DOUBLE AS RENT_ASKING_3_BED_MEAN_MONTHLY_CHANGE,
    (s.RENT_ASKING_3_BED_MEAN_QUARTERLY_CHANGE + 0e0)::DOUBLE AS RENT_ASKING_3_BED_MEAN_QUARTERLY_CHANGE,
    (s.RENT_ASKING_3_BED_MEAN_1_YEAR_CHANGE + 0e0)::DOUBLE AS RENT_ASKING_3_BED_MEAN_1_YEAR_CHANGE,
    (s.RENT_ASKING_3_BED_MEAN_3_YEAR_CHANGE + 0e0)::DOUBLE AS RENT_ASKING_3_BED_MEAN_3_YEAR_CHANGE,

    (s.RENT_ASKING_4_BED_MEAN + 0e0)::DOUBLE AS RENT_ASKING_4_BED_MEAN,
    (s.RENT_ASKING_4_BED_MEAN_MONTHLY_CHANGE + 0e0)::DOUBLE AS RENT_ASKING_4_BED_MEAN_MONTHLY_CHANGE,
    (s.RENT_ASKING_4_BED_MEAN_QUARTERLY_CHANGE + 0e0)::DOUBLE AS RENT_ASKING_4_BED_MEAN_QUARTERLY_CHANGE,
    (s.RENT_ASKING_4_BED_MEAN_1_YEAR_CHANGE + 0e0)::DOUBLE AS RENT_ASKING_4_BED_MEAN_1_YEAR_CHANGE,
    (s.RENT_ASKING_4_BED_MEAN_3_YEAR_CHANGE + 0e0)::DOUBLE AS RENT_ASKING_4_BED_MEAN_3_YEAR_CHANGE,

    (s.RENT_ASKING_5_BED_PLUS_MEAN + 0e0)::DOUBLE AS RENT_ASKING_5_BED_PLUS_MEAN,
    (s.RENT_ASKING_5_BED_PLUS_MEAN_MONTHLY_CHANGE + 0e0)::DOUBLE AS RENT_ASKING_5_BED_PLUS_MEAN_MONTHLY_CHANGE,
    (s.RENT_ASKING_5_BED_PLUS_MEAN_QUARTERLY_CHANGE + 0e0)::DOUBLE AS RENT_ASKING_5_BED_PLUS_MEAN_QUARTERLY_CHANGE,
    (s.RENT_ASKING_5_BED_PLUS_MEAN_1_YEAR_CHANGE + 0e0)::DOUBLE AS RENT_ASKING_5_BED_PLUS_MEAN_1_YEAR_CHANGE,
    (s.RENT_ASKING_5_BED_PLUS_MEAN_3_YEAR_CHANGE + 0e0)::DOUBLE AS RENT_ASKING_5_BED_PLUS_MEAN_3_YEAR_CHANGE,

    s.AS_OF_DATE::DATE AS AS_OF_DATE,
    TRIM(TO_VARCHAR(s.FORMAT)) AS FORMAT,
    s.INGESTED_AT::TIMESTAMP_NTZ AS INGESTED_AT,
    CURRENT_TIMESTAMP() AS dbt_updated_at
FROM {{ source('transform_markerr', 'markerr_rent_sfr') }} AS s
