#!/usr/bin/env python3
"""Legacy one-off generator for bridge-driven shells.

Prefer **metric_raw.csv** + **scripts/reference/catalog/build_metric_csv_from_metric_raw.py**
for REFERENCE.CATALOG.METRIC (see **docs/reference/METRIC_CSV_BUILD_SPEC.md**).
"""

from __future__ import annotations

import csv
from pathlib import Path


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    out = root / "seeds/reference/catalog/metric.csv"
    bridge_path = root / "seeds/reference/catalog/bridge_product_type_metric.csv"

    rows: list[dict[str, str]] = []

    def add(metric_id: str, spec: tuple) -> None:
        (
            metric_code,
            label,
            definition,
            concept,
            vendor,
            is_derived,
            src,
            unit,
            direction,
            geo,
            freq,
            is_active,
            dstatus,
            col,
            table,
            mcat,
            is_opco,
        ) = spec
        rows.append(
            {
                "metric_id": metric_id,
                "metric_code": metric_code,
                "metric_label": label,
                "definition": definition,
                "concept_code": concept,
                "vendor_code": vendor,
                "is_derived": "TRUE" if is_derived else "FALSE",
                "source_vendor_codes": src,
                "unit": unit,
                "direction": direction,
                "geo_level_code": geo,
                "frequency_code": freq,
                "is_active": "TRUE" if is_active else "FALSE",
                "data_status_code": dstatus,
                "snowflake_column": col,
                "table_path": table,
                "metric_category_code": mcat,
                "is_opco_metric": "TRUE" if is_opco else "FALSE",
            }
        )

    # Each tuple:
    # (metric_code, metric_label, definition, concept_code, vendor_code, is_derived, source_vendor_codes,
    #  unit, direction, geo_level_code, frequency_code, is_active, data_status_code, snowflake_column,
    #  table_path, metric_category_code, is_opco_metric)

    specs_active: list[tuple] = [
        (
            "bps_permits_measure_value",
            "Census BPS permit measure (CBSA)",
            "U.S. Census Building Permits Survey long-form VALUE on TRANSFORM.DEV.FACT_BPS_PERMITS_COUNTY (Jon TRANSFORM.BPS.PERMITS_COUNTY).",
            "permits",
            "census",
            False,
            "Census BPS",
            "varies",
            "neutral",
            "cbsa",
            "monthly",
            True,
            "active",
            "VALUE",
            "TRANSFORM.DEV.FACT_BPS_PERMITS_COUNTY",
            "leading",
            False,
        ),
        (
            "bls_laus_unemployment_rate_county",
            "BLS LAUS unemployment rate (county)",
            "BLS LAUS unemployment rate percent; MEASURE_CODE = 3 on TRANSFORM.DEV.FACT_BLS_LAUS_COUNTY.",
            "unemployment",
            "bls",
            False,
            "BLS LAUS",
            "pct",
            "negative",
            "county",
            "monthly",
            True,
            "active",
            "VALUE",
            "TRANSFORM.DEV.FACT_BLS_LAUS_COUNTY",
            "coincident",
            False,
        ),
        (
            "bls_laus_unemployed_persons_county",
            "BLS LAUS unemployed persons (county)",
            "BLS LAUS unemployed persons; MEASURE_CODE = 4 on TRANSFORM.DEV.FACT_BLS_LAUS_COUNTY.",
            "unemployment",
            "bls",
            False,
            "BLS LAUS",
            "count",
            "negative",
            "county",
            "monthly",
            True,
            "active",
            "VALUE",
            "TRANSFORM.DEV.FACT_BLS_LAUS_COUNTY",
            "coincident",
            False,
        ),
        (
            "bls_laus_employment_persons_county",
            "BLS LAUS employment (county)",
            "BLS LAUS employment level; MEASURE_CODE = 5 on TRANSFORM.DEV.FACT_BLS_LAUS_COUNTY.",
            "employment",
            "bls",
            False,
            "BLS LAUS",
            "count",
            "positive",
            "county",
            "monthly",
            True,
            "active",
            "VALUE",
            "TRANSFORM.DEV.FACT_BLS_LAUS_COUNTY",
            "coincident",
            False,
        ),
        (
            "bls_laus_labor_force_persons_county",
            "BLS LAUS labor force (county)",
            "BLS LAUS civilian labor force; MEASURE_CODE = 6 on TRANSFORM.DEV.FACT_BLS_LAUS_COUNTY.",
            "employment",
            "bls",
            False,
            "BLS LAUS",
            "count",
            "positive",
            "county",
            "monthly",
            True,
            "active",
            "VALUE",
            "TRANSFORM.DEV.FACT_BLS_LAUS_COUNTY",
            "coincident",
            False,
        ),
        (
            "bls_qcew_county_naics_employment",
            "BLS QCEW county NAICS employment (quarterly)",
            "QCEW employment headcount at county x NAICS-2 x quarter on TRANSFORM.DEV.FACT_BLS_QCEW_COUNTY_NAICS_QUARTERLY.",
            "employment",
            "bls",
            False,
            "BLS QCEW",
            "count",
            "positive",
            "county",
            "quarterly",
            True,
            "active",
            "employment",
            "TRANSFORM.DEV.FACT_BLS_QCEW_COUNTY_NAICS_QUARTERLY",
            "coincident",
            False,
        ),
        (
            "bls_qcew_county_naics_total_wages",
            "BLS QCEW county NAICS total quarterly wages",
            "QCEW total quarterly wages at county x NAICS-2 x quarter on TRANSFORM.DEV.FACT_BLS_QCEW_COUNTY_NAICS_QUARTERLY.",
            "employment",
            "bls",
            False,
            "BLS QCEW",
            "usd",
            "neutral",
            "county",
            "quarterly",
            True,
            "active",
            "total_wages",
            "TRANSFORM.DEV.FACT_BLS_QCEW_COUNTY_NAICS_QUARTERLY",
            "coincident",
            False,
        ),
        (
            "bls_qcew_county_naics_establishments",
            "BLS QCEW county NAICS establishment count",
            "QCEW establishment count at county x NAICS-2 x quarter on TRANSFORM.DEV.FACT_BLS_QCEW_COUNTY_NAICS_QUARTERLY.",
            "employment",
            "bls",
            False,
            "BLS QCEW",
            "count",
            "neutral",
            "county",
            "quarterly",
            True,
            "active",
            "establishments",
            "TRANSFORM.DEV.FACT_BLS_QCEW_COUNTY_NAICS_QUARTERLY",
            "coincident",
            False,
        ),
        (
            "bls_qcew_county_naics_avg_weekly_wage",
            "BLS QCEW county NAICS average weekly wage",
            "QCEW average weekly wage at county x NAICS-2 x quarter on TRANSFORM.DEV.FACT_BLS_QCEW_COUNTY_NAICS_QUARTERLY.",
            "employment",
            "bls",
            False,
            "BLS QCEW",
            "usd",
            "neutral",
            "county",
            "quarterly",
            True,
            "active",
            "avg_weekly_wage",
            "TRANSFORM.DEV.FACT_BLS_QCEW_COUNTY_NAICS_QUARTERLY",
            "coincident",
            False,
        ),
        (
            "bls_qcew_allocated_county_soc_estimated_employment",
            "QCEW-allocated county x SOC estimated employment",
            "QCEW/O*NET staffing model estimated employment by county x SOC on TRANSFORM.DEV.FACT_COUNTY_SOC_EMPLOYMENT.",
            "employment",
            "bls",
            True,
            "BLS QCEW;O*NET",
            "count",
            "positive",
            "county",
            "annual",
            True,
            "active",
            "estimated_employment",
            "TRANSFORM.DEV.FACT_COUNTY_SOC_EMPLOYMENT",
            "coincident",
            False,
        ),
        (
            "pretium_epoch_gwa_crosswalk_exposure_weight",
            "Epoch capability to O*NET GWA crosswalk (exposure_weight)",
            "Curated mapping weight 0-1 on TRANSFORM.DEV.REF_EPOCH_TO_GWA_CROSSWALK (not a geo time series).",
            "workforce_task_automation",
            "epoch_ai",
            False,
            "Epoch AI",
            "index",
            "neutral",
            "national",
            "annual",
            True,
            "active",
            "exposure_weight",
            "TRANSFORM.DEV.REF_EPOCH_TO_GWA_CROSSWALK",
            "leading",
            False,
        ),
        (
            "dol_onet_soc_gwa_activity_risk_score",
            "O*NET SOC GWA activity risk score",
            "Employment-weighted GWA exposure score by O*NET-SOC on TRANSFORM.DEV.FACT_DOL_ONET_SOC_GWA_ACTIVITY_RISK.",
            "workforce_task_automation",
            "onet",
            False,
            "O*NET",
            "index",
            "neutral",
            "national",
            "annual",
            True,
            "active",
            "gwa_activity_risk_score",
            "TRANSFORM.DEV.FACT_DOL_ONET_SOC_GWA_ACTIVITY_RISK",
            "leading",
            False,
        ),
        (
            "dol_onet_soc_work_context_friction_index",
            "O*NET SOC work-context friction index",
            "Composite friction index on TRANSFORM.DEV.FACT_DOL_ONET_SOC_CONTEXT_FRICTION.",
            "workforce_task_automation",
            "onet",
            False,
            "O*NET",
            "index",
            "neutral",
            "national",
            "annual",
            True,
            "active",
            "friction_index",
            "TRANSFORM.DEV.FACT_DOL_ONET_SOC_CONTEXT_FRICTION",
            "leading",
            False,
        ),
        (
            "dol_onet_soc_ai_friction_adjusted_exposure",
            "O*NET SOC friction-adjusted AI exposure",
            "Friction-adjusted exposure on TRANSFORM.DEV.FACT_DOL_ONET_SOC_AI_EXPOSURE.",
            "workforce_task_automation",
            "onet",
            False,
            "O*NET",
            "index",
            "neutral",
            "national",
            "annual",
            True,
            "active",
            "friction_adjusted_exposure",
            "TRANSFORM.DEV.FACT_DOL_ONET_SOC_AI_EXPOSURE",
            "leading",
            False,
        ),
        (
            "county_ai_replacement_risk_combined_score",
            "County AI replacement risk (combined score)",
            "Pretium-modeled county automation displacement composite on TRANSFORM.DEV.FACT_COUNTY_AI_REPLACEMENT_RISK (wide row).",
            "workforce_task_automation",
            "internal",
            True,
            "BLS;O*NET;Epoch",
            "index",
            "negative",
            "county",
            "annual",
            True,
            "active",
            "combined_risk_score",
            "TRANSFORM.DEV.FACT_COUNTY_AI_REPLACEMENT_RISK",
            "leading",
            False,
        ),
        (
            "cybersyn_hud_timeseries_value",
            "Cybersyn HUD housing timeseries (VALUE, county)",
            "HUD-aligned long-form VALUE at county grain on TRANSFORM.DEV.FACT_HUD_HOUSING_SERIES_COUNTY (Cybersyn housing_urban_development_*).",
            "occupancy",
            "cybersyn",
            False,
            "Cybersyn HUD",
            "varies",
            "neutral",
            "county",
            "monthly",
            True,
            "active",
            "VALUE",
            "TRANSFORM.DEV.FACT_HUD_HOUSING_SERIES_COUNTY",
            "coincident",
            False,
        ),
        (
            "cybersyn_hud_timeseries_value_cbsa",
            "Cybersyn HUD housing timeseries (VALUE, CBSA)",
            "HUD-aligned long-form VALUE at CBSA grain on TRANSFORM.DEV.FACT_HUD_HOUSING_SERIES_CBSA.",
            "occupancy",
            "cybersyn",
            False,
            "Cybersyn HUD",
            "varies",
            "neutral",
            "cbsa",
            "monthly",
            True,
            "active",
            "VALUE",
            "TRANSFORM.DEV.FACT_HUD_HOUSING_SERIES_CBSA",
            "coincident",
            False,
        ),
        (
            "cybersyn_irs_migration_by_characteristic_value",
            "Cybersyn IRS migration by characteristic (VALUE, county)",
            "IRS SOI migration stratified long-form VALUE on TRANSFORM.DEV.FACT_IRS_SOI_MIGRATION_BY_CHARACTERISTIC_ANNUAL_COUNTY.",
            "migration",
            "irs",
            False,
            "Cybersyn IRS",
            "varies",
            "neutral",
            "county",
            "annual",
            True,
            "active",
            "VALUE",
            "TRANSFORM.DEV.FACT_IRS_SOI_MIGRATION_BY_CHARACTERISTIC_ANNUAL_COUNTY",
            "leading",
            False,
        ),
        (
            "cybersyn_irs_migration_by_characteristic_value_cbsa",
            "Cybersyn IRS migration by characteristic (VALUE, CBSA)",
            "IRS SOI migration stratified long-form VALUE on TRANSFORM.DEV.FACT_IRS_SOI_MIGRATION_BY_CHARACTERISTIC_ANNUAL_CBSA.",
            "migration",
            "irs",
            False,
            "Cybersyn IRS",
            "varies",
            "neutral",
            "cbsa",
            "annual",
            True,
            "active",
            "VALUE",
            "TRANSFORM.DEV.FACT_IRS_SOI_MIGRATION_BY_CHARACTERISTIC_ANNUAL_CBSA",
            "leading",
            False,
        ),
        (
            "cybersyn_irs_od_migration_value",
            "Cybersyn IRS county OD migration (VALUE)",
            "IRS SOI county origin-destination migration long-form VALUE on TRANSFORM.DEV.FACT_IRS_SOI_ORIGIN_DESTINATION_MIGRATION_ANNUAL_COUNTY.",
            "migration",
            "irs",
            False,
            "Cybersyn IRS",
            "varies",
            "neutral",
            "county",
            "annual",
            True,
            "active",
            "VALUE",
            "TRANSFORM.DEV.FACT_IRS_SOI_ORIGIN_DESTINATION_MIGRATION_ANNUAL_COUNTY",
            "leading",
            False,
        ),
        (
            "cybersyn_irs_od_migration_value_cbsa",
            "Cybersyn IRS OD migration (VALUE, CBSA-attributed)",
            "CBSA-attributed OD migration long-form VALUE on TRANSFORM.DEV.FACT_IRS_SOI_ORIGIN_DESTINATION_MIGRATION_ANNUAL_CBSA.",
            "migration",
            "irs",
            False,
            "Cybersyn IRS",
            "varies",
            "neutral",
            "cbsa",
            "annual",
            True,
            "active",
            "VALUE",
            "TRANSFORM.DEV.FACT_IRS_SOI_ORIGIN_DESTINATION_MIGRATION_ANNUAL_CBSA",
            "leading",
            False,
        ),
        (
            "cybersyn_fhfa_house_price_timeseries_value",
            "FHFA house price Cybersyn timeseries (VALUE, county)",
            "FHFA HPI long-form VALUE at county grain on TRANSFORM.DEV.FACT_FHFA_HOUSE_PRICE_COUNTY.",
            "homeprice",
            "fhfa",
            False,
            "Cybersyn FHFA",
            "varies",
            "neutral",
            "county",
            "monthly",
            True,
            "active",
            "VALUE",
            "TRANSFORM.DEV.FACT_FHFA_HOUSE_PRICE_COUNTY",
            "coincident",
            False,
        ),
        (
            "cybersyn_fhfa_house_price_timeseries_value_cbsa",
            "FHFA house price Cybersyn timeseries (VALUE, CBSA)",
            "FHFA HPI long-form VALUE at CBSA grain on TRANSFORM.DEV.FACT_FHFA_HOUSE_PRICE_CBSA.",
            "homeprice",
            "fhfa",
            False,
            "Cybersyn FHFA",
            "varies",
            "neutral",
            "cbsa",
            "monthly",
            True,
            "active",
            "VALUE",
            "TRANSFORM.DEV.FACT_FHFA_HOUSE_PRICE_CBSA",
            "coincident",
            False,
        ),
        (
            "cybersyn_fhfa_mortgage_performance_value_county",
            "FHFA mortgage performance (VALUE, county)",
            "FHFA mortgage performance long-form VALUE at county grain on TRANSFORM.DEV.FACT_FHFA_MORTGAGE_PERFORMANCE_COUNTY.",
            "delinquency",
            "fhfa",
            False,
            "Cybersyn FHFA",
            "varies",
            "negative",
            "county",
            "monthly",
            True,
            "active",
            "VALUE",
            "TRANSFORM.DEV.FACT_FHFA_MORTGAGE_PERFORMANCE_COUNTY",
            "lagging",
            False,
        ),
        (
            "cybersyn_fhfa_mortgage_performance_value_cbsa",
            "FHFA mortgage performance (VALUE, CBSA)",
            "FHFA mortgage performance long-form VALUE at CBSA grain on TRANSFORM.DEV.FACT_FHFA_MORTGAGE_PERFORMANCE_CBSA.",
            "delinquency",
            "fhfa",
            False,
            "Cybersyn FHFA",
            "varies",
            "negative",
            "cbsa",
            "monthly",
            True,
            "active",
            "VALUE",
            "TRANSFORM.DEV.FACT_FHFA_MORTGAGE_PERFORMANCE_CBSA",
            "lagging",
            False,
        ),
        (
            "cybersyn_fhfa_uniform_appraisal_value_county",
            "FHFA uniform appraisal (VALUE, county)",
            "FHFA UAD long-form VALUE at county grain on TRANSFORM.DEV.FACT_FHFA_UNIFORM_APPRAISAL_COUNTY.",
            "homeprice",
            "fhfa",
            False,
            "Cybersyn FHFA",
            "varies",
            "neutral",
            "county",
            "monthly",
            True,
            "active",
            "VALUE",
            "TRANSFORM.DEV.FACT_FHFA_UNIFORM_APPRAISAL_COUNTY",
            "coincident",
            False,
        ),
        (
            "cybersyn_fhfa_uniform_appraisal_value_cbsa",
            "FHFA uniform appraisal (VALUE, CBSA)",
            "FHFA UAD long-form VALUE at CBSA grain on TRANSFORM.DEV.FACT_FHFA_UNIFORM_APPRAISAL_CBSA.",
            "homeprice",
            "fhfa",
            False,
            "Cybersyn FHFA",
            "varies",
            "neutral",
            "cbsa",
            "monthly",
            True,
            "active",
            "VALUE",
            "TRANSFORM.DEV.FACT_FHFA_UNIFORM_APPRAISAL_CBSA",
            "coincident",
            False,
        ),
        (
            "freddie_mac_housing_timeseries_value",
            "Freddie Mac housing timeseries (VALUE)",
            "Freddie Mac PMMS and related long-form VALUE on TRANSFORM.DEV.FACT_FREDDIE_MAC_HOUSING_NATIONAL_WEEKLY.",
            "cap_rate",
            "freddie_mac",
            False,
            "Freddie Mac",
            "varies",
            "neutral",
            "national",
            "weekly",
            True,
            "active",
            "VALUE",
            "TRANSFORM.DEV.FACT_FREDDIE_MAC_HOUSING_NATIONAL_WEEKLY",
            "coincident",
            False,
        ),
        (
            "lehd_lodes_od_bg_jobs_total",
            "LEHD LODES OD jobs total (BG x BG)",
            "LEHD LODES origin-destination jobs JOBS_TOTAL on TRANSFORM.DEV.FACT_LODES_OD_BG.",
            "employment",
            "lehd",
            False,
            "LEHD LODES",
            "count",
            "positive",
            "block_group",
            "annual",
            True,
            "active",
            "JOBS_TOTAL",
            "TRANSFORM.DEV.FACT_LODES_OD_BG",
            "coincident",
            False,
        ),
        (
            "markerr_rent_property_cbsa_avg_rent_effective",
            "Markerr MF CBSA average effective rent",
            "Markerr MF CBSA monthly effective rent on TRANSFORM.DEV.FACT_MARKERR_RENT_PROPERTY_CBSA_MONTHLY.",
            "rent",
            "markerr",
            False,
            "Markerr",
            "usd",
            "positive",
            "cbsa",
            "monthly",
            True,
            "active",
            "AVG_RENT_EFFECTIVE",
            "TRANSFORM.DEV.FACT_MARKERR_RENT_PROPERTY_CBSA_MONTHLY",
            "coincident",
            False,
        ),
        (
            "markerr_rent_property_cbsa_avg_rent_asking",
            "Markerr MF CBSA average asking rent",
            "Markerr MF CBSA monthly asking rent on TRANSFORM.DEV.FACT_MARKERR_RENT_PROPERTY_CBSA_MONTHLY.",
            "rent",
            "markerr",
            False,
            "Markerr",
            "usd",
            "positive",
            "cbsa",
            "monthly",
            True,
            "active",
            "AVG_RENT_ASKING",
            "TRANSFORM.DEV.FACT_MARKERR_RENT_PROPERTY_CBSA_MONTHLY",
            "coincident",
            False,
        ),
        (
            "costar_scenarios_market_effective_rent_per_unit",
            "CoStar scenarios market effective rent per unit",
            "CoStar SCENARIOS wide column MARKET_EFFECTIVE_RENT_PER_UNIT on TRANSFORM.DEV.FACT_COSTAR_SCENARIOS.",
            "rent",
            "costar",
            False,
            "CoStar",
            "usd",
            "neutral",
            "cbsa",
            "monthly",
            True,
            "active",
            "MARKET_EFFECTIVE_RENT_PER_UNIT",
            "TRANSFORM.DEV.FACT_COSTAR_SCENARIOS",
            "coincident",
            False,
        ),
        (
            "costar_scenarios_market_asking_rent_per_unit",
            "CoStar scenarios market asking rent per unit",
            "CoStar SCENARIOS wide column MARKET_ASKING_RENT_PER_UNIT on TRANSFORM.DEV.FACT_COSTAR_SCENARIOS.",
            "rent",
            "costar",
            False,
            "CoStar",
            "usd",
            "neutral",
            "cbsa",
            "monthly",
            True,
            "active",
            "MARKET_ASKING_RENT_PER_UNIT",
            "TRANSFORM.DEV.FACT_COSTAR_SCENARIOS",
            "coincident",
            False,
        ),
        (
            "yardi_matrix_marketperformance_bh_datavalue",
            "Yardi Matrix market performance DATAVALUE (long-form)",
            "Yardi Matrix MARKETPERFORMANCE_BH long-form DATAVALUE on TRANSFORM.DEV.FACT_YARDI_MATRIX_MARKETPERFORMANCE_BH.",
            "rent",
            "yardi",
            False,
            "Yardi Matrix",
            "varies",
            "neutral",
            "cbsa",
            "monthly",
            True,
            "active",
            "DATAVALUE",
            "TRANSFORM.DEV.FACT_YARDI_MATRIX_MARKETPERFORMANCE_BH",
            "coincident",
            False,
        ),
        (
            "zillow_rentals_metric_value",
            "Zillow research rentals long-form (METRIC_VALUE)",
            "Zillow research rentals unpivot on TRANSFORM.DEV.FACT_ZILLOW_RENTALS.",
            "rent",
            "zillow",
            False,
            "Zillow",
            "varies",
            "neutral",
            "zip",
            "monthly",
            True,
            "active",
            "METRIC_VALUE",
            "TRANSFORM.DEV.FACT_ZILLOW_RENTALS",
            "coincident",
            False,
        ),
        (
            "zillow_days_on_market_and_price_cuts_metric_value",
            "Zillow DOM and price cuts long-form (METRIC_VALUE)",
            "Zillow research DOM/price cuts unpivot on TRANSFORM.DEV.FACT_ZILLOW_DAYS_ON_MARKET_AND_PRICE_CUTS.",
            "listings",
            "zillow",
            False,
            "Zillow",
            "varies",
            "neutral",
            "zip",
            "monthly",
            True,
            "active",
            "METRIC_VALUE",
            "TRANSFORM.DEV.FACT_ZILLOW_DAYS_ON_MARKET_AND_PRICE_CUTS",
            "leading",
            False,
        ),
        (
            "zillow_for_sale_listings_metric_value",
            "Zillow for-sale listings long-form (METRIC_VALUE)",
            "Zillow research for-sale listings unpivot on TRANSFORM.DEV.FACT_ZILLOW_FOR_SALE_LISTINGS.",
            "listings",
            "zillow",
            False,
            "Zillow",
            "varies",
            "neutral",
            "zip",
            "monthly",
            True,
            "active",
            "METRIC_VALUE",
            "TRANSFORM.DEV.FACT_ZILLOW_FOR_SALE_LISTINGS",
            "coincident",
            False,
        ),
        (
            "progress_fund_spine_property_number",
            "SFDC property number (Progress fund spine)",
            "External property identifier on TRANSFORM.DEV.CONCEPT_PROGRESS_PROPERTY (sf_properties__PROPERTYNUMBER__C).",
            "fund_property_spine",
            "salesforce",
            False,
            "Salesforce;Yardi",
            "varies",
            "neutral",
            "property",
            "varies",
            True,
            "active",
            "sf_properties__PROPERTYNUMBER__C",
            "TRANSFORM.DEV.CONCEPT_PROGRESS_PROPERTY",
            "coincident",
            True,
        ),
        (
            "progress_fund_spine_cap_rate",
            "SFDC cap rate (Progress fund spine)",
            "Cap rate percent on TRANSFORM.DEV.CONCEPT_PROGRESS_PROPERTY (sf_properties__CAP_RATE__C).",
            "fund_property_spine",
            "salesforce",
            False,
            "Salesforce",
            "pct",
            "neutral",
            "property",
            "varies",
            True,
            "active",
            "sf_properties__CAP_RATE__C",
            "TRANSFORM.DEV.CONCEPT_PROGRESS_PROPERTY",
            "coincident",
            True,
        ),
        (
            "progress_fund_spine_gross_yield",
            "SFDC gross yield (Progress fund spine)",
            "Gross yield on TRANSFORM.DEV.CONCEPT_PROGRESS_PROPERTY (sf_properties__GROSS_YIELD__C).",
            "fund_property_spine",
            "salesforce",
            False,
            "Salesforce",
            "pct",
            "positive",
            "property",
            "varies",
            True,
            "active",
            "sf_properties__GROSS_YIELD__C",
            "TRANSFORM.DEV.CONCEPT_PROGRESS_PROPERTY",
            "coincident",
            True,
        ),
        (
            "progress_fund_spine_home_condition_score",
            "SFDC home condition score (Progress fund spine)",
            "Home condition score on TRANSFORM.DEV.CONCEPT_PROGRESS_PROPERTY (sf_properties__HOME_CONDITION_SCORE__C).",
            "fund_property_spine",
            "salesforce",
            False,
            "Salesforce",
            "index",
            "neutral",
            "property",
            "varies",
            True,
            "active",
            "sf_properties__HOME_CONDITION_SCORE__C",
            "TRANSFORM.DEV.CONCEPT_PROGRESS_PROPERTY",
            "coincident",
            True,
        ),
        (
            "progress_fund_spine_yardi_tier",
            "Yardi property tier (Progress fund spine)",
            "Yardi PROPATTRIBUTES tier on TRANSFORM.DEV.CONCEPT_PROGRESS_PROPERTY (yardi_propattr__TIER).",
            "fund_property_spine",
            "yardi",
            False,
            "Yardi;Salesforce",
            "varies",
            "neutral",
            "property",
            "varies",
            True,
            "active",
            "yardi_propattr__TIER",
            "TRANSFORM.DEV.CONCEPT_PROGRESS_PROPERTY",
            "coincident",
            True,
        ),
        (
            "progress_fund_spine_yardi_property_status",
            "Yardi property status (Progress fund spine)",
            "Yardi PROPATTRIBUTES property status on TRANSFORM.DEV.CONCEPT_PROGRESS_PROPERTY (yardi_propattr__PROPERTY_STATUS).",
            "fund_property_spine",
            "yardi",
            False,
            "Yardi;Salesforce",
            "varies",
            "neutral",
            "property",
            "varies",
            True,
            "active",
            "yardi_propattr__PROPERTY_STATUS",
            "TRANSFORM.DEV.CONCEPT_PROGRESS_PROPERTY",
            "coincident",
            True,
        ),
        (
            "progress_acquisition_uw_acquisition_purchase_price",
            "Acquisition contract purchase price (UW stack)",
            "SFDC_ACQUISITION__C purchase price on TRANSFORM.DEV.CONCEPT_PROGRESS_ACQUISITION_UW (acquisition__PURCHASE_PRICE__C).",
            "acquisition_underwriting",
            "salesforce",
            False,
            "Salesforce",
            "usd",
            "neutral",
            "property",
            "varies",
            True,
            "active",
            "acquisition__PURCHASE_PRICE__C",
            "TRANSFORM.DEV.CONCEPT_PROGRESS_ACQUISITION_UW",
            "coincident",
            True,
        ),
        (
            "progress_acquisition_uw_acquisition_cap_rate",
            "Acquisition cap rate (UW stack)",
            "SFDC_ACQUISITION__C cap rate on TRANSFORM.DEV.CONCEPT_PROGRESS_ACQUISITION_UW (acquisition__CAP_RATE__C).",
            "acquisition_underwriting",
            "salesforce",
            False,
            "Salesforce",
            "pct",
            "neutral",
            "property",
            "varies",
            True,
            "active",
            "acquisition__CAP_RATE__C",
            "TRANSFORM.DEV.CONCEPT_PROGRESS_ACQUISITION_UW",
            "coincident",
            True,
        ),
        (
            "progress_acquisition_uw_acquisition_net_yield",
            "Acquisition net yield (UW stack)",
            "SFDC_ACQUISITION__C net yield on TRANSFORM.DEV.CONCEPT_PROGRESS_ACQUISITION_UW (acquisition__NET_YIELD__C).",
            "acquisition_underwriting",
            "salesforce",
            False,
            "Salesforce",
            "pct",
            "neutral",
            "property",
            "varies",
            True,
            "active",
            "acquisition__NET_YIELD__C",
            "TRANSFORM.DEV.CONCEPT_PROGRESS_ACQUISITION_UW",
            "coincident",
            True,
        ),
        (
            "progress_acquisition_uw_fdd_purchase_price",
            "Finance DD purchase price (UW stack)",
            "SFDC_FINANCE_DUE_DILIGENCE__C purchase price on TRANSFORM.DEV.CONCEPT_PROGRESS_ACQUISITION_UW (fdd__PURCHASE_PRICE__C).",
            "acquisition_underwriting",
            "salesforce",
            False,
            "Salesforce",
            "usd",
            "neutral",
            "property",
            "varies",
            True,
            "active",
            "fdd__PURCHASE_PRICE__C",
            "TRANSFORM.DEV.CONCEPT_PROGRESS_ACQUISITION_UW",
            "coincident",
            True,
        ),
        (
            "progress_acquisition_uw_fdd_closing_date",
            "Finance DD closing date (UW stack)",
            "SFDC_FINANCE_DUE_DILIGENCE__C closing date on TRANSFORM.DEV.CONCEPT_PROGRESS_ACQUISITION_UW (fdd__CLOSING_DATE__C).",
            "acquisition_underwriting",
            "salesforce",
            False,
            "Salesforce",
            "varies",
            "neutral",
            "property",
            "varies",
            True,
            "active",
            "fdd__CLOSING_DATE__C",
            "TRANSFORM.DEV.CONCEPT_PROGRESS_ACQUISITION_UW",
            "coincident",
            True,
        ),
        (
            "progress_acquisition_uw_fdd_stabilized",
            "Finance DD stabilized flag (UW stack)",
            "SFDC_FINANCE_DUE_DILIGENCE__C stabilized indicator on TRANSFORM.DEV.CONCEPT_PROGRESS_ACQUISITION_UW (fdd__STABILIZED__C).",
            "acquisition_underwriting",
            "salesforce",
            False,
            "Salesforce",
            "varies",
            "neutral",
            "property",
            "varies",
            True,
            "active",
            "fdd__STABILIZED__C",
            "TRANSFORM.DEV.CONCEPT_PROGRESS_ACQUISITION_UW",
            "coincident",
            True,
        ),
    ]

    active_bridge: set[str] = set()
    with bridge_path.open(newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if row["is_active"].strip() in ("1",):
                active_bridge.add(row["metric_code"])

    active_specs = {s[0] for s in specs_active}
    missing = sorted(active_bridge - active_specs)
    extra = sorted(active_specs - active_bridge)
    if missing or extra:
        raise SystemExit(f"Active spec mismatch missing={missing} extra={extra}")

    for i, spec in enumerate(specs_active, start=1):
        add(f"MET_{i:03d}", spec)

    start = len(specs_active) + 1

    specs_inactive: list[tuple] = [
        (
            "census_pep_cbsa_annual_observe",
            "Census PEP CBSA annual population (observe)",
            "Baseline registration for TRANSFORM.DEV.FACT_CENSUS_PEP_CBSA_ANNUAL (multi-column population components).",
            "population",
            "census",
            False,
            "Census",
            "count",
            "positive",
            "cbsa",
            "annual",
            False,
            "under_review",
            "MULTI_COLUMN",
            "TRANSFORM.DEV.FACT_CENSUS_PEP_CBSA_ANNUAL",
            "coincident",
            False,
        ),
        (
            "census_pep_county_annual_observe",
            "Census PEP county annual population (observe)",
            "Baseline registration for TRANSFORM.DEV.FACT_CENSUS_PEP_COUNTY_ANNUAL (multi-column population components).",
            "population",
            "census",
            False,
            "Census",
            "count",
            "positive",
            "county",
            "annual",
            False,
            "under_review",
            "MULTI_COLUMN",
            "TRANSFORM.DEV.FACT_CENSUS_PEP_COUNTY_ANNUAL",
            "coincident",
            False,
        ),
        (
            "realtor_inventory_cbsa_observe",
            "Realtor inventory CBSA (observe)",
            "Long-form Realtor inventory series on TRANSFORM.DEV.FACT_REALTOR_INVENTORY_CBSA (metric_id + VALUE).",
            "absorption",
            "realtor",
            False,
            "Realtor",
            "varies",
            "neutral",
            "cbsa",
            "monthly",
            False,
            "under_review",
            "VALUE",
            "TRANSFORM.DEV.FACT_REALTOR_INVENTORY_CBSA",
            "coincident",
            False,
        ),
        (
            "markerr_rent_sfr_observe",
            "Markerr SFR rent fact (observe)",
            "Baseline registration for TRANSFORM.DEV.FACT_MARKERR_RENT_SFR (promote specific series later).",
            "rent",
            "markerr",
            False,
            "Markerr",
            "varies",
            "neutral",
            "zip",
            "monthly",
            False,
            "under_review",
            "MULTI_COLUMN",
            "TRANSFORM.DEV.FACT_MARKERR_RENT_SFR",
            "coincident",
            False,
        ),
        (
            "costar_mf_market_cbsa_monthly_observe",
            "CoStar MF market CBSA monthly export (observe)",
            "Wide CoStar MF DataExport read-through on TRANSFORM.DEV.FACT_COSTAR_MF_MARKET_CBSA_MONTHLY; defer per-column MET until inventory completes.",
            "rent",
            "costar",
            False,
            "CoStar",
            "varies",
            "neutral",
            "cbsa",
            "monthly",
            False,
            "under_review",
            "MULTI_COLUMN",
            "TRANSFORM.DEV.FACT_COSTAR_MF_MARKET_CBSA_MONTHLY",
            "coincident",
            False,
        ),
        (
            "oxford_amreg_quarterly_observe",
            "Oxford AMREG CBSA quarterly series (observe)",
            "Long-form Oxford AMREG indicators on TRANSFORM.DEV.FACT_OXFORD_AMREG_QUARTERLY (metric_id + VALUE).",
            "employment",
            "oxford_economics",
            False,
            "Oxford Economics",
            "varies",
            "neutral",
            "cbsa",
            "varies",
            False,
            "under_review",
            "VALUE",
            "TRANSFORM.DEV.FACT_OXFORD_AMREG_QUARTERLY",
            "coincident",
            False,
        ),
        (
            "oxford_wdmarco_quarterly_observe",
            "Oxford WDMARCO national quarterly series (observe)",
            "Long-form Oxford WDMARCO indicators on TRANSFORM.DEV.FACT_OXFORD_WDMARCO_QUARTERLY (metric_id + VALUE).",
            "employment",
            "oxford_economics",
            False,
            "Oxford Economics",
            "varies",
            "neutral",
            "national",
            "varies",
            False,
            "under_review",
            "VALUE",
            "TRANSFORM.DEV.FACT_OXFORD_WDMARCO_QUARTERLY",
            "coincident",
            False,
        ),
        (
            "zillow_home_values_observe",
            "Zillow home values long-form (observe)",
            "Zillow research home values unpivot on TRANSFORM.DEV.FACT_ZILLOW_HOME_VALUES.",
            "homeprice",
            "zillow",
            False,
            "Zillow",
            "varies",
            "neutral",
            "zip",
            "monthly",
            False,
            "under_review",
            "METRIC_VALUE",
            "TRANSFORM.DEV.FACT_ZILLOW_HOME_VALUES",
            "coincident",
            False,
        ),
        (
            "zillow_sales_observe",
            "Zillow sales long-form (observe)",
            "Zillow research sales unpivot on TRANSFORM.DEV.FACT_ZILLOW_SALES.",
            "transactions",
            "zillow",
            False,
            "Zillow",
            "varies",
            "neutral",
            "zip",
            "monthly",
            False,
            "under_review",
            "METRIC_VALUE",
            "TRANSFORM.DEV.FACT_ZILLOW_SALES",
            "coincident",
            False,
        ),
        (
            "zillow_affordability_observe",
            "Zillow affordability long-form (observe)",
            "Zillow research affordability unpivot on TRANSFORM.DEV.FACT_ZILLOW_AFFORDABILITY.",
            "homeprice",
            "zillow",
            False,
            "Zillow",
            "varies",
            "neutral",
            "zip",
            "monthly",
            False,
            "under_review",
            "METRIC_VALUE",
            "TRANSFORM.DEV.FACT_ZILLOW_AFFORDABILITY",
            "coincident",
            False,
        ),
        (
            "zillow_home_values_forecasts_observe",
            "Zillow home value forecasts long-form (observe)",
            "Zillow research home value forecasts unpivot on TRANSFORM.DEV.FACT_ZILLOW_HOME_VALUES_FORECASTS.",
            "homeprice",
            "zillow",
            False,
            "Zillow",
            "varies",
            "neutral",
            "zip",
            "monthly",
            False,
            "under_review",
            "METRIC_VALUE",
            "TRANSFORM.DEV.FACT_ZILLOW_HOME_VALUES_FORECASTS",
            "coincident",
            False,
        ),
        (
            "zillow_market_heat_index_observe",
            "Zillow market heat index long-form (observe)",
            "Zillow research market heat index unpivot on TRANSFORM.DEV.FACT_ZILLOW_MARKET_HEAT_INDEX.",
            "absorption",
            "zillow",
            False,
            "Zillow",
            "varies",
            "neutral",
            "zip",
            "monthly",
            False,
            "under_review",
            "METRIC_VALUE",
            "TRANSFORM.DEV.FACT_ZILLOW_MARKET_HEAT_INDEX",
            "leading",
            False,
        ),
        (
            "zillow_new_construction_observe",
            "Zillow new construction long-form (observe)",
            "Zillow research new construction unpivot on TRANSFORM.DEV.FACT_ZILLOW_NEW_CONSTRUCTION.",
            "homeprice",
            "zillow",
            False,
            "Zillow",
            "varies",
            "neutral",
            "zip",
            "monthly",
            False,
            "under_review",
            "METRIC_VALUE",
            "TRANSFORM.DEV.FACT_ZILLOW_NEW_CONSTRUCTION",
            "coincident",
            False,
        ),
        (
            "zillow_rental_forecasts_observe",
            "Zillow rental forecasts long-form (observe)",
            "Zillow research rental forecasts unpivot on TRANSFORM.DEV.FACT_ZILLOW_RENTAL_FORECASTS.",
            "rent",
            "zillow",
            False,
            "Zillow",
            "varies",
            "neutral",
            "zip",
            "monthly",
            False,
            "under_review",
            "METRIC_VALUE",
            "TRANSFORM.DEV.FACT_ZILLOW_RENTAL_FORECASTS",
            "coincident",
            False,
        ),
        (
            "fhfa_house_price_observe",
            "FHFA house price umbrella (observe-only)",
            "Compatibility umbrella table TRANSFORM.DEV.FACT_FHFA_HOUSE_PRICE (mixed geo); prefer sliced county/CBSA monthly facts for governed reads.",
            "homeprice",
            "fhfa",
            False,
            "Cybersyn FHFA",
            "varies",
            "neutral",
            "unmapped",
            "monthly",
            False,
            "under_review",
            "VALUE",
            "TRANSFORM.DEV.FACT_FHFA_HOUSE_PRICE",
            "coincident",
            False,
        ),
        (
            "fhfa_uniform_appraisal_observe",
            "FHFA uniform appraisal umbrella (observe-only)",
            "Compatibility umbrella table TRANSFORM.DEV.FACT_FHFA_UNIFORM_APPRAISAL (mixed geo); prefer sliced county/CBSA monthly facts.",
            "homeprice",
            "fhfa",
            False,
            "Cybersyn FHFA",
            "varies",
            "neutral",
            "unmapped",
            "monthly",
            False,
            "under_review",
            "VALUE",
            "TRANSFORM.DEV.FACT_FHFA_UNIFORM_APPRAISAL",
            "coincident",
            False,
        ),
        (
            "yardi_matrix_submarketmatch_zipzcta_bh_observe",
            "Yardi Matrix ZIP/ZCTA submarket match (observe-only)",
            "ZIP/ZCTA crosswalk-style table TRANSFORM.DEV.FACT_YARDI_MATRIX_SUBMARKETMATCH_ZIPZCTA_BH; not a measure series — keep observe-only.",
            "occupancy",
            "yardi",
            False,
            "Yardi Matrix",
            "varies",
            "neutral",
            "zip",
            "monthly",
            False,
            "under_review",
            "MULTI_COLUMN",
            "TRANSFORM.DEV.FACT_YARDI_MATRIX_SUBMARKETMATCH_ZIPZCTA_BH",
            "coincident",
            False,
        ),
        (
            "cherre_vacant_h3_r8_mf_vacant_parcels",
            "Cherre vacant MF parcels at H3 R8 (planned)",
            "Placeholder for Cherre vacant-parcel housing_stock universe FACT; not MLS active-listing inventory.",
            "housing_stock",
            "cherre",
            False,
            "Cherre",
            "count",
            "neutral",
            "cbsa",
            "monthly",
            False,
            "under_review",
            "MULTI_COLUMN",
            "TRANSFORM.DEV.FACT_CHERRE_VACANT_H3_R8_MF_VACANT_PARCELS_PLANNED",
            "lagging",
            False,
        ),
        (
            "rent_median_psf_zip_monthly_planned",
            "Rent median PSF ZIP monthly (planned)",
            "Placeholder for future rent PSF median FACT at ZIP monthly grain (ties metric_derived_input backlog).",
            "rent",
            "internal",
            True,
            "Internal",
            "usd",
            "neutral",
            "zip",
            "monthly",
            False,
            "under_review",
            "MULTI_COLUMN",
            "TRANSFORM.DEV.FACT_RENT_MEDIAN_PSF_ZIP_MONTHLY_PLANNED",
            "coincident",
            False,
        ),
        (
            "cybersyn_acs5_median_household_income_county_planned",
            "ACS5 median household income county (planned)",
            "Placeholder for future Cybersyn/ACS5 median household income FACT at county grain.",
            "income",
            "cybersyn",
            False,
            "Cybersyn ACS",
            "usd",
            "positive",
            "county",
            "annual",
            False,
            "under_review",
            "VALUE",
            "TRANSFORM.DEV.FACT_ACS5_MEDIAN_HOUSEHOLD_INCOME_COUNTY_PLANNED",
            "coincident",
            False,
        ),
        (
            "supply_pipeline_under_construction_units_county_planned",
            "Under construction units county (planned)",
            "Placeholder for future supply-pipeline under-construction units FACT at county grain.",
            "supply_pipeline",
            "internal",
            True,
            "Internal",
            "count",
            "neutral",
            "county",
            "monthly",
            False,
            "under_review",
            "MULTI_COLUMN",
            "TRANSFORM.DEV.FACT_SUPPLY_PIPELINE_UNDER_CONSTRUCTION_UNITS_COUNTY_PLANNED",
            "leading",
            False,
        ),
        (
            "cherre_recorder_sale_transactions_county_planned",
            "Cherre recorder sale transactions county (planned)",
            "Placeholder for future Cherre recorder sale transactions FACT at county grain.",
            "transactions",
            "cherre",
            False,
            "Cherre",
            "count",
            "neutral",
            "county",
            "monthly",
            False,
            "under_review",
            "MULTI_COLUMN",
            "TRANSFORM.DEV.FACT_CHERRE_RECORDER_SALE_TRANSACTIONS_COUNTY_PLANNED",
            "coincident",
            False,
        ),
        (
            "markerr_rent_listings_county_cnt_multi_family",
            "Markerr county MF listing counts (planned)",
            "Placeholder for future Markerr county MF listing counts FACT (wide/long TBD).",
            "supply_pipeline",
            "markerr",
            False,
            "Markerr",
            "count",
            "neutral",
            "county",
            "monthly",
            False,
            "under_review",
            "MULTI_COLUMN",
            "TRANSFORM.DEV.FACT_MARKERR_RENT_LISTINGS_COUNTY_CNT_MULTI_FAMILY_PLANNED",
            "leading",
            False,
        ),
    ]

    inactive_bridge: set[str] = set()
    with bridge_path.open(newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if row["is_active"].strip() not in ("1",):
                inactive_bridge.add(row["metric_code"])

    inactive_specs = {s[0] for s in specs_inactive}
    missing_i = sorted(inactive_bridge - inactive_specs)
    extra_i = sorted(inactive_specs - inactive_bridge)
    if missing_i or extra_i:
        raise SystemExit(f"Inactive spec mismatch missing={missing_i} extra={extra_i}")

    for j, spec in enumerate(specs_inactive, start=start):
        add(f"MET_{j:03d}", spec)

    next_id = len(rows) + 1

    extras: list[tuple] = [
        (
            "bls_laus_cbsa_series_observe",
            "BLS LAUS CBSA series (observe-only)",
            "BLS LAUS as published at CBSA grain on TRANSFORM.DEV.FACT_BLS_LAUS_CBSA_MONTHLY; prefer county rollups for OMB-aligned CBSA ids.",
            "unemployment",
            "bls",
            False,
            "BLS LAUS",
            "varies",
            "neutral",
            "cbsa",
            "monthly",
            True,
            "under_review",
            "VALUE",
            "TRANSFORM.DEV.FACT_BLS_LAUS_CBSA_MONTHLY",
            "coincident",
            False,
        ),
        (
            "lodes_od_h3_r8_annual_jobs_total_observe",
            "LODES OD H3 R8 annual jobs total (observe)",
            "Origin-destination jobs at H3 R8 pair grain on TRANSFORM.DEV.FACT_LODES_OD_H3_R8_ANNUAL.",
            "employment",
            "lehd",
            False,
            "LEHD LODES",
            "count",
            "positive",
            "cbsa",
            "annual",
            False,
            "under_review",
            "JOBS_TOTAL",
            "TRANSFORM.DEV.FACT_LODES_OD_H3_R8_ANNUAL",
            "coincident",
            False,
        ),
        (
            "lodes_od_workplace_hex_annual_job_inflow_total_observe",
            "LODES workplace hex annual job inflow total (observe)",
            "Workplace-hex inbound jobs aggregate on TRANSFORM.DEV.FACT_LODES_OD_WORKPLACE_HEX_ANNUAL.",
            "employment",
            "lehd",
            False,
            "LEHD LODES",
            "count",
            "positive",
            "cbsa",
            "annual",
            False,
            "under_review",
            "JOB_INFLOW_TOTAL",
            "TRANSFORM.DEV.FACT_LODES_OD_WORKPLACE_HEX_ANNUAL",
            "coincident",
            False,
        ),
        (
            "lodes_h3r8_workplace_gravity_job_inflow_total_observe",
            "LODES H3 R8 workplace gravity job inflow total (observe)",
            "Workplace gravity job inflow totals on TRANSFORM.DEV.FACT_LODES_H3R8_WORKPLACE_GRAVITY.",
            "employment",
            "lehd",
            False,
            "LEHD LODES",
            "count",
            "positive",
            "cbsa",
            "annual",
            False,
            "under_review",
            "JOB_INFLOW_TOTAL",
            "TRANSFORM.DEV.FACT_LODES_H3R8_WORKPLACE_GRAVITY",
            "coincident",
            False,
        ),
        (
            "lodes_nearest_center_h3_r8_annual_observe",
            "LODES nearest employment-center distances H3 R8 (observe)",
            "Hex-level nearest-center distances and strengths on TRANSFORM.DEV.FACT_LODES_NEAREST_CENTER_H3_R8_ANNUAL (multi-column).",
            "employment",
            "lehd",
            True,
            "LEHD LODES;corridor centers",
            "varies",
            "neutral",
            "cbsa",
            "annual",
            False,
            "under_review",
            "MULTI_COLUMN",
            "TRANSFORM.DEV.FACT_LODES_NEAREST_CENTER_H3_R8_ANNUAL",
            "coincident",
            False,
        ),
        (
            "aige_counties_series_observe",
            "AIGE county automation index (observe)",
            "Long-form AIGE scores from TRANSFORM.DEV.FACT_AIGE_COUNTIES (gated `aige_counties_enabled`).",
            "workforce_task_automation",
            "internal",
            False,
            "AIGE",
            "index",
            "neutral",
            "county",
            "annual",
            False,
            "under_review",
            "VALUE",
            "TRANSFORM.DEV.FACT_AIGE_COUNTIES",
            "leading",
            False,
        ),
        (
            "transform_concept_employment_cbsa_monthly_observe",
            "TRANSFORM.CONCEPT employment CBSA monthly (observe)",
            "Read-through of TRANSFORM.CONCEPT.EMPLOYMENT_CBSA_MONTHLY via TRANSFORM.DEV.FACT_TRANSFORM_CONCEPT_EMPLOYMENT_CBSA_MONTHLY.",
            "employment",
            "internal",
            True,
            "TRANSFORM.CONCEPT",
            "varies",
            "neutral",
            "cbsa",
            "monthly",
            False,
            "under_review",
            "MULTI_COLUMN",
            "TRANSFORM.DEV.FACT_TRANSFORM_CONCEPT_EMPLOYMENT_CBSA_MONTHLY",
            "coincident",
            False,
        ),
        (
            "transform_concept_employment_county_monthly_observe",
            "TRANSFORM.CONCEPT employment county monthly (observe)",
            "Read-through of TRANSFORM.CONCEPT.EMPLOYMENT_COUNTY_MONTHLY via TRANSFORM.DEV.FACT_TRANSFORM_CONCEPT_EMPLOYMENT_COUNTY_MONTHLY.",
            "employment",
            "internal",
            True,
            "TRANSFORM.CONCEPT",
            "varies",
            "neutral",
            "county",
            "monthly",
            False,
            "under_review",
            "MULTI_COLUMN",
            "TRANSFORM.DEV.FACT_TRANSFORM_CONCEPT_EMPLOYMENT_COUNTY_MONTHLY",
            "coincident",
            False,
        ),
    ]

    for spec in extras:
        add(f"MET_{next_id:03d}", spec)
        next_id += 1

    # Auto-append observe metrics for any TRANSFORM.DEV FACT_* models not covered above.
    covered_tables = {r["table_path"] for r in rows}

    def infer_vendor_concept_geo(stem: str) -> tuple[str, str, str, bool]:
        """Return (vendor_code, concept_code, geo_level_code, is_opco_metric)."""
        s = stem.lower()
        if s.startswith("fact_sfdc_"):
            if "acquisition" in s or "fdd" in s or "finance_due_diligence" in s:
                return "salesforce", "acquisition_underwriting", "property", True
            if "bpo" in s or "disposition" in s or "concession" in s:
                return "salesforce", "fund_property_spine", "property", True
            return "salesforce", "fund_property_spine", "property", True

        if s.startswith("fact_se_yardi_") or s.startswith("fact_bh_yardi_") or s.startswith("fact_progress_yardi_"):
            return "yardi", "fund_property_spine", "property", True

        if "fhfa" in s:
            if "mortgage_performance" in s:
                return "fhfa", "delinquency", "unmapped", False
            if "uniform_appraisal" in s:
                return "fhfa", "homeprice", "unmapped", False
            return "fhfa", "homeprice", "unmapped", False

        if "hud_housing" in s:
            return "cybersyn", "occupancy", "unmapped", False

        if "irs_soi_migration_by_characteristic_annual" in s and s.endswith("annual") and "county" not in s and "cbsa" not in s:
            return "irs", "migration", "unmapped", False

        return "internal", "employment", "unmapped", False

    models_root = root / "models" / "transform" / "dev"
    for p in sorted(models_root.rglob("fact_*.sql")):
        stem = p.stem  # fact_*
        assert stem.startswith("fact_")
        table_path = "TRANSFORM.DEV.FACT_" + stem[len("fact_") :].upper()
        if table_path in covered_tables:
            continue

        slug = stem[len("fact_") :]
        metric_code = slug + "_observe"
        label = slug.replace("_", " ").title() + " (observe)"
        definition = f"Baseline catalog registration for {table_path} (wide/multi-column; promote specific columns after consumer contract is pinned)."

        vendor, concept, geo_level, is_opco = infer_vendor_concept_geo(stem)
        frequency = "monthly" if stem.lower().endswith("_monthly") else "varies"

        add(
            f"MET_{next_id:03d}",
            (
                metric_code,
                label,
                definition,
                concept,
                vendor,
                True,
                vendor.upper(),
                "varies",
                "neutral",
                geo_level,
                frequency,
                False,
                "under_review",
                "MULTI_COLUMN",
                table_path,
                "coincident",
                is_opco,
            ),
        )
        next_id += 1
        covered_tables.add(table_path)

    fieldnames = [
        "metric_id",
        "metric_code",
        "metric_label",
        "definition",
        "concept_code",
        "vendor_code",
        "is_derived",
        "source_vendor_codes",
        "unit",
        "direction",
        "geo_level_code",
        "frequency_code",
        "is_active",
        "data_status_code",
        "snowflake_column",
        "table_path",
        "metric_category_code",
        "is_opco_metric",
    ]

    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        w.writerows(rows)

    print(f"wrote {len(rows)} metric rows to {out}")


if __name__ == "__main__":
    main()
