-- SERVING.DEMO — portfolio rollup delivery shape (pretium **DISPOSITION_YIELD_PORTFOLIO** contract).
-- **mart_updated_at** ← **dbt_updated_at** on **model_disposition_yield_portfolio**.
{{ config(
    materialized='view',
    alias='DISPOSITION_YIELD_PORTFOLIO',
    enabled=var('transform_dev_enable_disposition_yield_stack', false),
    tags=['serving', 'demo', 'disposition', 'ic_market_analysis'],
) }}

SELECT
    fund_id,
    fund_name,
    cbsa_code,
    cbsa_title,
    state,
    disposition_stage,
    row_id,
    total_properties,
    sold_count,
    active_pipeline_count,
    properties_with_valuation,
    properties_with_rent,
    total_valuation_avm,
    avg_valuation_avm,
    median_valuation_avm,
    min_valuation_avm,
    max_valuation_avm,
    total_net_proceeds,
    avg_net_proceeds,
    total_purchase_price,
    avg_purchase_price,
    total_gain_loss,
    avg_gain_loss,
    avg_gain_loss_pct,
    total_net_gain_loss,
    total_annual_rent,
    avg_monthly_rent,
    median_monthly_rent,
    avg_gross_yield_on_avm_pct,
    median_gross_yield_on_avm_pct,
    avg_gross_yield_on_cost_pct,
    portfolio_gross_yield_pct,
    avg_days_on_market,
    median_days_on_market,
    avg_avm_per_sqft,
    avg_square_feet,
    avg_bedrooms,
    count_bpo_as_is,
    count_proposed_as_is,
    count_listing_agent_bpo,
    count_no_valuation,
    dbt_updated_at AS mart_updated_at
FROM {{ ref('model_disposition_yield_portfolio') }}
