-- SERVING.DEMO — thin delivery surface aligned with pretium-ai-dbt **EDW_PROD.DELIVERY.DISPOSITION_YIELD_PROPERTY**
-- (column contract + **mart_updated_at** alias from **dbt_updated_at**). Source: **concept_disposition_yield_property**.
{{ config(
    materialized='view',
    database=var('serving_database', 'SERVING'),
    schema='DEMO',
    alias='DISPOSITION_YIELD_PROPERTY',
    enabled=var('transform_dev_enable_disposition_yield_stack', false),
    tags=['serving', 'demo', 'disposition', 'ic_market_analysis'],
) }}

SELECT
    disposition_id,
    property_sfdc_id,
    tribeca_number,
    property_number,
    row_id,
    opco_id,
    fund_id,
    fund_name,
    offering_id,
    cbsa_code,
    cbsa_title,
    state,
    state_name,
    county_fips,
    county_name,
    city,
    zip_code,
    property_type,
    bedrooms,
    bathrooms,
    square_feet,
    year_built,
    is_active,
    property_status,
    stage,
    disposition_stage,
    sub_stage,
    awaiting_decision_to_sell,
    proposed_for_disposition,
    reason_for_disposition,
    reason_for_disposition_notes,
    type_of_sale,
    channel,
    channel_type,
    is_1031_exchange,
    valuation_avm,
    valuation_source,
    bpo_as_is_value,
    bpo_repaired_value,
    bpo_30day_as_is_value,
    bpo_completed_date,
    proposed_as_is_value,
    listing_agent_bpo_as_is_value,
    bpo_reviewer_repaired_value,
    purchase_price,
    transaction_cost_pct,
    net_proceeds,
    gain_loss,
    gain_loss_pct,
    net_gain_loss,
    monthly_rent,
    annual_rent,
    gross_yield_on_avm_pct,
    gross_yield_on_cost_pct,
    avm_per_sqft,
    original_list_price,
    list_price,
    current_list_price,
    contract_price,
    property_sold_price,
    financing_type,
    earnest_money_deposit,
    sfdc_estimated_net_proceeds,
    estimated_closing_costs,
    actual_closing_costs,
    days_on_market,
    property_listed_date,
    estimated_disposition_date,
    property_sold_date,
    offer_date,
    is_sold,
    created_date,
    last_modified_date,
    dbt_updated_at AS mart_updated_at
FROM {{ ref('concept_disposition_yield_property') }}
